@BASE_URL = http://localhost:3005/api

GET {{BASE_URL}}

###
GET {{BASE_URL}}/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMDc5ZjgwZjUxMzA2MzA2YTgzM2EiLCJpYXQiOjE2MjAwNTI3NTcsImV4cCI6MTYyMDA1NjM1N30.kN3GrxN8AGEAsUGmgUeivAe5ZaOZKte_oyBB-cQwErc

###
GET {{BASE_URL}}/admin/532

###
POST {{BASE_URL}}/admin
Content-Type: application/json

{
    "name": "admin3",
    "email": "admin3@hotmail.com",
    "userName": "admin3",
    "password": "123456"

}

###
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email": "admin2@hotmail.com",
    "password": "123456"
}

###
PATCH {{BASE_URL}}/admin/608d50e9791cde4fb0ee7551
Content-Type: application/json

{
    "userName": "asfasfas",
    "password":"1534asf25"   
}

###
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhkNTM1MzNjOTdlYzIwZDRiY2YxOTAiLCJpYXQiOjE2MTk5NjI4ODIsImV4cCI6MTYxOTk2NjQ4Mn0.eG4EUWTOgZjuL9sqKHpZ-ZtaFWnLbsIk2U4nwq9uook

{
    "userName": "halil",
    "password":"1534asf25"   
}

###
DELETE {{BASE_URL}}/admin/609009cd64920d3500e2d749
Content-Type: application/json

###
DELETE   {{BASE_URL}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhlZjM5ODIwNmI4ZTJjMTBkY2Q5OWIiLCJpYXQiOjE2MjAwNTI3MzQsImV4cCI6MTYyMDA1NjMzNH0.zI4Pg7ugfykdjovnrCIt8_2H3kzUKqvS7c7m7YaFiQA

###
GET  {{BASE_URL}}/admin/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhlYjE0OTEyZDM0MjE4M2NhZDYzZjEiLCJpYXQiOjE2MjAwNTI1NDQsImV4cCI6MTYyMDA1NjE0NH0.SLfcKcsjsfFUAGSEJvXqrE2MkeIbsvX4mTwGOVN2lbo
