@BASE_URL = http://localhost:3000/api

GET {{BASE_URL}}

###
GET {{BASE_URL}}/users

###
GET {{BASE_URL}}/users/532

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name":"halil",
    "age": 23,
    "UserName": "halilozat"
}

###
PATCH {{BASE_URL}}/users/554
Content-Type: application/json

{
    "name":"halil3",
    "age": 23,
    "UserName": "halilozat3"
}

###
DELETE {{BASE_URL}}/users/554
Content-Type: application/json
