@BASE_URL = http://localhost:3005/api

GET {{BASE_URL}}

###
GET {{BASE_URL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhlYjE0OTEyZDM0MjE4M2NhZDYzZjEiLCJpYXQiOjE2MTk5ODEwOTAsImV4cCI6MTYxOTk4NDY5MH0.-8Bt93ihwszEXp4nRvVHrjFo6cft_5me-F8DxLt9RRA

###
GET {{BASE_URL}}/users/532

###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@hotmail.com",
    "userName": "admin",
    "password": "123456"

}

###
POST {{BASE_URL}}/users/login
Content-Type: application/json

{
    "email": "admin@hotmail.com",
    "password": "123456"
}

###
PATCH {{BASE_URL}}/users/608d50e9791cde4fb0ee7551
Content-Type: application/json

{
    "userName": "asfasfas",
    "password":"1534asf25"   
}

###
PATCH {{BASE_URL}}/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhkNTM1MzNjOTdlYzIwZDRiY2YxOTAiLCJpYXQiOjE2MTk5NjI4ODIsImV4cCI6MTYxOTk2NjQ4Mn0.eG4EUWTOgZjuL9sqKHpZ-ZtaFWnLbsIk2U4nwq9uook

{
    "userName": "halil",
    "password":"1534asf25"   
}

###
DELETE {{BASE_URL}}/users/608ac33213dc8614842ab997
Content-Type: application/json


DELETE   {{BASE_URL}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhkNTM1MzNjOTdlYzIwZDRiY2YxOTAiLCJpYXQiOjE2MTk5NjI4ODIsImV4cCI6MTYxOTk2NjQ4Mn0.eG4EUWTOgZjuL9sqKHpZ-ZtaFWnLbsIk2U4nwq9uook


GET  {{BASE_URL}}/users/deleteAll
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhkNTM1MzNjOTdlYzIwZDRiY2YxOTAiLCJpYXQiOjE2MTk5NjI4ODIsImV4cCI6MTYxOTk2NjQ4Mn0.eG4EUWTOgZjuL9sqKHpZ-ZtaFWnLbsIk2U4nwq9uook
